### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by angelbaal2008** [648540858/wvp-pro-assist#11]
023-06-13 17:48:59.408  INFO 8403 --- [           main] t.panll.assist.WvpProAssistApplication   : Started WvpProAssistApplication in 9.055 seconds (JVM running for 10.26)
java.lang.IllegalArgumentException: This binary '/root/bin/ffmpeg' is not a supported version of ffprobe
        at net.bramp.ffmpeg.FFprobe.checkIfFFprobe(FFprobe.java:70)
        at net.bramp.ffmpeg.FFprobe.probe(FFprobe.java:83)
        at net.bramp.ffmpeg.FFprobe.probe(FFprobe.java:48)
        at top.panll.assist.service.VideoFileService.handFile(VideoFileService.java:131)
        at top.panll.assist.config.StartConfig.run(StartConfig.java:86)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at top.panll.assist.WvpProAssistApplication.main(WvpProAssistApplication.java:12)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
2023-06-13 17:48:59.430 ERROR 8403 --- [           main] top.panll.assist.config.StartConfig      : 环境错误： This binary '/root/bin/ffmpeg' is not a supported version of ffprobe

**Comment by 1002victor** [comment]
我也遇到了，解决了吗

**Comment by dodu2014** [comment]
我在windows环境运行也报错，发到这了：https://github.com/648540858/wvp-GB28181-pro/issues/974

**Comment by 648540858** [comment]
ffmpeg没配置
