### ISSUE TITLE
Error creating bean with name 'FFmpegExecUtils' defined in URL

### ISSUE THREAD

**Issue by melon-gg** [648540858/wvp-pro-assist#3]
启动wvp辅助云端录像包报错
java -jar -Dspring.config.location=application-assit.yml wvp-pro-assist-1.0.0-20220406094716.jar
`
2022-04-06 17:51:22.827  INFO 2465649 --- [           main] t.panll.assist.WvpProAssistApplication   : Starting WvpProAssistApplication v1.0.0 on gpu-1080-elec-36 with PID 2465649 (/home/pai/Downloads/wvp/serverV2/wvp-pro-assist-master/target/wvp-pro-assist-1.0.0-20220406094716.jar started by pai in /home/pai/Downloads/wvp/serverV2/wvp-pro-assist-master/target)
2022-04-06 17:51:22.830  INFO 2465649 --- [           main] t.panll.assist.WvpProAssistApplication   : No active profile set, falling back to default profiles: default
2022-04-06 17:51:25.596  WARN 2465649 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'startConfig': Unsatisfied dependency expressed through field 'videoFileService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'videoFileService': Unsatisfied dependency expressed through field 'ffmpegExecUtils'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'FFmpegExecUtils' defined in URL [jar:file:/home/pai/Downloads/wvp/serverV2/wvp-pro-assist-master/target/wvp-pro-assist-1.0.0-20220406094716.jar!/BOOT-INF/classes!/top/panll/assist/service/FFmpegExecUtils.class]: Invocation of init method failed; nested exception is java.io.IOException: /usr/bin/ffmpeg returned non-zero exit status. Check stdout.
2022-04-06 17:51:25.638 ERROR 2465649 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'startConfig': Unsatisfied dependency expressed through field 'videoFileService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'videoFileService': Unsatisfied dependency expressed through field 'ffmpegExecUtils'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'FFmpegExecUtils' defined in URL [jar:file:/home/pai/Downloads/wvp/serverV2/wvp-pro-assist-master/target/wvp-pro-assist-1.0.0-20220406094716.jar!/BOOT-INF/classes!/top/panll/assist/service/FFmpegExecUtils.class]: Invocation of init method failed; nested exception is java.io.IOException: /usr/bin/ffmpeg returned non-zero exit status. Check stdout.
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1420) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) ~[spring-beans-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) ~[spring-context-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) ~[spring-context-5.2.10.RELEASE.jar!/:5.2.10.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405) [spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.5.RELEASE.jar!/:2.3.5.RELEASE]
	at top.panll.assist.WvpProAssistApplication.main(WvpProAssistApplication.java:12) [classes!/:1.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_312]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [wvp-pro-assist-1.0.0-20220406094716.jar:1.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) [wvp-pro-assist-1.0.0-20220406094716.jar:1.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [wvp-pro-assist-1.0.0-20220406094716.jar:1.0.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [wvp-pro-assist-1.0.0-20220406094716.jar:1.0.0]`

**Comment by yflisa** [comment]
修改下启动的配置文件，本人使用的是 `application-dev.yml， userSettings.ffmpeg 项和 userSettings.ffprobe 项的路径。
